print("Operaciones Basicas")
n1=input("Escribe un numero: ")
n2=input("Escribe otro numero: ")
suma=eval(n1)+eval(n2)
print(n1, "+", n2, "=", suma)
resta=eval(n1)-eval(n2)
print(n1, "-", n2, "=", resta)
mult=eval(n1)*eval(n2)
print(n1, "x", n2, "=", mult)
div=eval(n1)/eval(n2)
print(n1, "/", n2, "=", div)
divent=eval(n1)//eval(n2)
print(n1, "//", n2, "=", divent, "(division entera)")
resto=eval(n1)%eval(n2)
print(n1, "%", n2, "=", resto, "(resto)")