print("Analizador de palabras")
palabra=input("Escribe una palabra:")
print("La palabra",palabra,"tiene",len(palabra),"caracteres")
print("La primera letra es:",(palabra[:1]))
print("La ultima letra es:",(palabra[-1:]))
print("Las dos primeras letras son:",(palabra[:2]))
print("Las dos ultimas letras son:",(palabra[-2:]))